import type { VercelRequest, VercelResponse } from '@vercel/node';

// Check if we have API key
const hasApiKey = !!process.env.GEMINI_API_KEY;

interface GenerateRequest {
  type: 'draft' | 'improve' | 'shorten' | 'expand' | 'hashtags';
  tone?: string;
  platform?: string;
  currentText?: string;
  topic?: string;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Enable CORS for local development
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { type, tone, platform, currentText, topic } = req.body as GenerateRequest;

  if (!type) {
    return res.status(400).json({ error: 'Missing type parameter' });
  }

  // Mock mode if no API key
  if (!hasApiKey) {
    console.log('[Mock Mode] No GEMINI_API_KEY configured, returning mock content');
    return res.json({
      content: getMockContent(type, topic, currentText, platform),
      mock: true
    });
  }

  try {
    const { GoogleGenerativeAI } = await import('@google/generative-ai');
    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

    let prompt = '';

    switch (type) {
      case 'draft':
        if (!topic) {
          return res.status(400).json({ error: 'Topic is required for drafting' });
        }
        prompt = `Write a ${tone || 'professional'} social media post for ${platform || 'general social media'} about: "${topic}". Include relevant emojis and hashtags. Keep it concise and engaging.`;
        break;

      case 'improve':
        if (!currentText) {
          return res.status(400).json({ error: 'Current text is required for improvement' });
        }
        prompt = `Rewrite the following social media post to be more engaging and polished for ${platform || 'social media'}. Keep the original meaning but improve the flow, clarity, and impact:\n\n"${currentText}"`;
        break;

      case 'shorten':
        if (!currentText) {
          return res.status(400).json({ error: 'Current text is required for shortening' });
        }
        prompt = `Shorten the following post for ${platform || 'social media'} while keeping the key message. ${platform === 'twitter' ? 'Maximum 280 characters.' : 'Keep it concise.'}\n\n"${currentText}"`;
        break;

      case 'expand':
        if (!currentText) {
          return res.status(400).json({ error: 'Current text is required for expansion' });
        }
        prompt = `Expand on the following post ideas to make it a more comprehensive, thought-provoking piece for ${platform || 'social media'}. Add depth and value:\n\n"${currentText}"`;
        break;

      case 'hashtags':
        if (!currentText) {
          return res.status(400).json({ error: 'Current text is required for hashtag generation' });
        }
        prompt = `Generate 10 relevant, high-traffic hashtags for a ${platform || 'social media'} post about: "${currentText}". Return only the hashtags separated by spaces, nothing else.`;
        break;

      default:
        return res.status(400).json({ error: 'Invalid type parameter' });
    }

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    res.json({ content: text });
  } catch (error) {
    console.error('AI generation error:', error);
    res.status(500).json({ error: 'Failed to generate content' });
  }
}

// Mock content for local development without API key
function getMockContent(type: string, topic?: string, currentText?: string, platform?: string): string {
  switch (type) {
    case 'draft':
      return `✨ Here's an amazing post about ${topic || 'your topic'}!\n\nThis is mock content for local development. Connect your Gemini API key for real AI generation.\n\n#MockContent #LocalDev #${platform || 'SocialMedia'}`;
    case 'improve':
      return `🚀 ${currentText}\n\n[Enhanced version - connect Gemini API for real improvements]`;
    case 'shorten':
      return (currentText?.substring(0, 100) || '') + '... ✂️';
    case 'expand':
      return `${currentText}\n\n📝 This is expanded content that would normally be generated by AI. Connect your Gemini API key for real content expansion with valuable insights and engaging details.`;
    case 'hashtags':
      return '#ContentCreation #SocialMedia #Marketing #Digital #Growth #Engagement #Strategy #Branding #Online #Success';
    default:
      return 'Mock content for local development';
  }
}
